---

- name: Habilitamos puertos usados por la SDN 8285 UDP
  firewalld:
    port: 8285/udp
    permanent: true
    state: enabled
  become: yes
  
- name: Habilitamos puertos usados por la SDN 8472 UDP
  firewalld:
    port: 8472/udp
    permanent: true
    state: enabled
  become: yes

- name: Reiniciando Firewall 
  systemd:
    name: firewalld
    state: restarted
  become: yes