---

- name: 10250 tcp y 30000-32767 tcp
  command: firewall-cmd --zone=public --permanent --add-port={{ item }}
  with_items:
    - 10250/tcp
    - 30000-32767/tcp

- name: Reinicio firewall
  command: firewall-cmd --reload