---

- name: Instalar chrony
  dnf:
    name: "chrony"
    state: present

- name: Iniciar servicio chrony
  systemd:
    name: chronyd
    state: started
    enabled: yes
    masked: no
  become: yes

- name: NTP a true 
  command: /usr/bin/timedatectl set-ntp true