---

- name: Instalar chrony
  dnf:
    name: "chrony"
    state: present

- name: Habilita chrony
  command: /usr/bin/systemctl enable chronyd

- name: Inicia chrony
  command: /usr/bin/systemctl start chronyd

- name: NTP a true 
  command: /usr/bin/timedatectl set-ntp true