---

- name: Habilitar Firewalld 
  systemd:
    name: firewalld
    state: started
  become: yes

- name: Abrir los puertos del firewall
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - nfs
    - rpc-bind
    - mountd

- name: Reiniciando el servicio Firewalld 
  systemd:
    name: firewalld
    state: reloaded
  become: yes